services:
  bot:
    build: .
    container_name: time_agent_bot
    env_file:
      - .env
    environment:
      - TZ=${TZ:-Asia/Tashkent}
    volumes:
      - ./logs:/app/logs
      - app_data:/app/data
      - C:/time-agent-secrets:/run/secrets:ro
    ports:
      - "8085:8085"
    restart: always

volumes:
  app_data: